### ISSUE TITLE
Implementation Error

### ISSUE THREAD

**Issue by ikp-773** [arnold-parge/screen_loader#1]
Showing Error
![Screen Shot 2020-07-11 at 5 00 25 PM](https://user-images.githubusercontent.com/57410559/87223153-1dc33880-c398-11ea-8b47-47e57b73efbe.png)

**Comment by arnold-parge** [comment]
Replace `build()` function with `screen()` function.
Check the example.

**Comment by ikp-773** [comment]
Thank You😊
