### ISSUE TITLE
How to know when the screen is loading? v4.0.0

### ISSUE THREAD

**Issue by eliasjtg** [arnold-parge/screen_loader#10]
I have issues migrating to last version, i can't know when the screen is loading, in previous version it has `isLoading` variable

**Comment by eliasjtg** [comment]
Maybe expose the `ScreenLoaderStream`?

**Comment by arnold-parge** [comment]
Thanks for pointing it out, I'll add back the `isLoading` property.

**Comment by arnold-parge** [comment]
Added `isLoading` property in `v4.0.1`.
