### ISSUE TITLE
How to handle exceptions?

### ISSUE THREAD

**Issue by magnuswikhog** [arnold-parge/screen_loader#12]
I just tried out this widget, and I noticed that if I throw an exception inside the method used in `performFuture()`, the loading screen never disappears. In my case, I don't want to catch the exception inside the method.

Is it possible to make the loader disappear in case the method throws an exception? Or would it be possible to add this feature (perhaps with an optional `bool hideOnError` flag in `performFuture()`)?

**Comment by arnold-parge** [comment]
Try `stopLoading();` to stop the loading whenever you want.
